### ISSUE TITLE
Plugin name mismatch in Gradle Portal

### ISSUE THREAD

**Issue by jmcgarr** [nebula-plugins/nebula-plugin-plugin#28]
I tried to use the plugin via the README.md and gradle says it can't find the plugin. The docs are pointing to 'nebula.plugin-plugin', but I can see this plugin was published as ['nebula.nebula-plugin'](https://plugins.gradle.org/plugin/nebula.nebula-plugin). The last time this was published was in January 2015 and it was 2.2.0 of the plugin, but the source shows it is now up to 3.1.1.

Did I miss something?

**Comment by rspieldenner** [comment]
Will update docs.

**Comment by jmcgarr** [comment]
Should we be publishing as well?

**Comment by rspieldenner** [comment]
And check on that.

**Comment by rspieldenner** [comment]
Yep getting this error (will talk to Gradle):

    * What went wrong:
    Execution failed for task ':publishPlugins'.
    > Failed to post to server.
      Server responded with:
      The user 'nebula' does not have write permissions to: nebula.plugin-plugin'

**Comment by rspieldenner** [comment]
Fixed
