### ISSUE TITLE
can not apply  this plugin on subproject 

### ISSUE THREAD

**Issue by foxundermoon** [nebula-plugins/nebula-plugin-plugin#34]
root project as plugin project is OK.
but as subproject is  failure
```
* What went wrong:
An exception occurred applying plugin request [id: 'nebula.plugin-plugin', version: '5.6.0']
> Failed to apply plugin [id 'nebula.nebula-release']
   > Could not get unknown property 'release' for task set of type org.gradle.api.internal.tasks.DefaultTaskContainer.

```

**Comment by rspieldenner** [comment]
You need at least the nebula.release plugin applied to the root,
nebula.plugin-plugin applies the release plugin. Also I would recommend
using the nebula.plugin-plugin as an example of how to write a project
plugin and non necessarily take our opinions as your opinions.

**Comment by AzyCrw4282** [comment]
adding this to plugin fixed it

```
    id 'maven-publish'
```
