### ISSUE TITLE
Gradle publish plugin and upcoming Gradle 8 compatibility

### ISSUE THREAD

**Issue by ljacomet** [nebula-plugins/nebula-plugin-plugin#71]
Hey Nebula team 👋 ,

Dependency on the Gradle publish plugin has been [upgraded to 1.0.0](https://github.com/nebula-plugins/nebula-plugin-plugin/commit/18d808645be95a842d216430fdbf4c8e1eb241f2) 🎉 

However, with upcoming Gradle 8, the `pluginBundle` extension is no longer registered. So the `gradlePlugin` extension, obtained with the `java-gradle-plugin`, which is always applied by `publish-plugin` 1.0.0, is to be used exclusively.

Gradle 7.6 will be a transition version, where `pluginBundle` remains but `gradlePlugin` has the full set of properties, like `tags`.

And unfortunately, Gradle < 7.5 will still require you to use the `pluginBundle` for things like `tags`.

So I am not sure what's the easiest for this plugin to navigate this upgrade, but it would be great to have a version that would be 7.6 / 8.0 ready by not relying anymore on `pluginBundle`.

**Comment by rpalcolea** [comment]
Alright, `com.gradle.plugin-publish` 1.1.0 fixed the issue above

I went ahead and changed our plugin to configure vcsUrl and website via `gradlePlugin` now and released in `v20.0.0` 

I'll roll out to all consumers 👍 

Thanks for bringing this up @ljacomet
