### ISSUE TITLE
Validation errors for plugin tasks

### ISSUE THREAD

**Issue by ljacomet** [nebula-plugins/nebula-plugin-plugin#72]
When running the smoke tests we have in Gradle, this plugin still fails static validation with the following errors:

```
> Plugin validation failed with 4 problems:
    - Error: Type 'com.gradle.publish.PublishExistingTask' property 'fileRepositoryRoot' is annotated with @InputDirectory but missing a normalization strategy.
      
      Reason: If you don't declare the normalization, outputs can't be re-used between machines or locations on the same machine, therefore caching efficiency drops significantly.
      
      Possible solution: Declare the normalization strategy by annotating the property with either @PathSensitive, @Classpath or @CompileClasspath.
      
      For more information, please refer to https://docs.gradle.org/8.5/userguide/validation_problems.html#missing_normalization_annotation in the Gradle documentation.
    - Warning: Type 'com.gradle.publish.LoginTask' must be annotated either with @CacheableTask or with @DisableCachingByDefault.
      
      Reason: The task author should make clear why a task is not cacheable.
      
      Possible solutions:
        1. Add @DisableCachingByDefault(because = ...).
        2. Add @CacheableTask.
        3. Add @UntrackedTask(because = ...).
      
      For more information, please refer to https://docs.gradle.org/8.5/userguide/validation_problems.html#disable_caching_by_default in the Gradle documentation.
    - Warning: Type 'com.gradle.publish.PublishExistingTask' must be annotated either with @CacheableTask or with @DisableCachingByDefault.
      
      Reason: The task author should make clear why a task is not cacheable.
      
      Possible solutions:
        1. Add @DisableCachingByDefault(because = ...).
        2. Add @CacheableTask.
        3. Add @UntrackedTask(because = ...).
      
      For more information, please refer to https://docs.gradle.org/8.5/userguide/validation_problems.html#disable_caching_by_default in the Gradle documentation.
    - Warning: Type 'com.gradle.publish.PublishTask' must be annotated either with @CacheableTask or with @DisableCachingByDefault.
      
      Reason: The task author should make clear why a task is not cacheable.
      
      Possible solutions:
        1. Add @DisableCachingByDefault(because = ...).
        2. Add @CacheableTask.
        3. Add @UntrackedTask(because = ...).
      
      For more information, please refer to https://docs.gradle.org/8.5/userguide/validation_problems.html#disable_caching_by_default in the Gradle documentation.
  For more on how to annotate task properties, please refer to https://docs.gradle.org/8.5/userguide/incremental_build.html#sec:task_input_output_annotations in the Gradle documentation.
```

You should be able to reproduce this by running the `validatePlugins` task from the `java-gradle-plugin`.

Or you can run the following with a [recent Gradle checkout](https://github.com/gradle/gradle/), after commenting out the line [around here](https://github.com/gradle/gradle/blob/6ec1a01aae678e6c833483db98014e202f5db29a/subprojects/smoke-test/src/smokeTest/groovy/org/gradle/smoketests/NebulaPluginsSmokeTest.groovy#L242):
`./gradlew smoke-test:smokeTest --tests NebulaPluginsSmokeTest`

**Comment by rpalcolea** [comment]
Hi @ljacomet 

Thanks for bringing this up

I'm a little confused here. Looking at the output locally, I see this:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':validatePluginWithId_com_gradle_plugin-publish'.
> Plugin validation failed with 4 problems:
    - Error: Type 'com.gradle.publish.PublishExistingTask' property 'fileRepositoryRoot' is annotated with @InputDirectory but missing a normalization strategy.
      
      Reason: If you don't declare the normalization, outputs can't be re-used between machines or locations on the same machine, therefore caching efficiency drops significantly.
      
      Possible solution: Declare the normalization strategy by annotating the property with either @PathSensitive, @Classpath or @CompileClasspath.
      
      For more information, please refer to https://docs.gradle.org/8.7-20240110080000+0000/userguide/validation_problems.html#missing_normalization_annotation in the Gradle documentation.
    - Warning: Type 'com.gradle.publish.LoginTask' must be annotated either with @CacheableTask or with @DisableCachingByDefault.
      
      Reason: The task author should make clear why a task is not cacheable.
      
      Possible solutions:
        1. Add @DisableCachingByDefault(because = ...).
        2. Add @CacheableTask.
        3. Add @UntrackedTask(because = ...).
      
      For more information, please refer to https://docs.gradle.org/8.7-20240110080000+0000/userguide/validation_problems.html#disable_caching_by_default in the Gradle documentation.
    - Warning: Type 'com.gradle.publish.PublishExistingTask' must be annotated either with @CacheableTask or with @DisableCachingByDefault.
      
      Reason: The task author should make clear why a task is not cacheable.
      
      Possible solutions:
        1. Add @DisableCachingByDefault(because = ...).
        2. Add @CacheableTask.
        3. Add @UntrackedTask(because = ...).
      
      For more information, please refer to https://docs.gradle.org/8.7-20240110080000+0000/userguide/validation_problems.html#disable_caching_by_default in the Gradle documentation.
    - Warning: Type 'com.gradle.publish.PublishTask' must be annotated either with @CacheableTask or with @DisableCachingByDefault.
      
      Reason: The task author should make clear why a task is not cacheable.
      
      Possible solutions:
        1. Add @DisableCachingByDefault(because = ...).
        2. Add @CacheableTask.
        3. Add @UntrackedTask(because = ...).
      
      For more information, please refer to https://docs.gradle.org/8.7-20240110080000+0000/userguide/validation_problems.html#disable_caching_by_default in the Gradle documentation.
  For more on how to annotate task properties, please refer to https://docs.gradle.org/8.7-20240110080000+0000/userguide/incremental_build.html#sec:task_input_output_annotations in the Gradle documentation.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

This suggests that the issue is coming from `com.gradle.publish:plugin-publish-plugin` 

We bundle the plugin via https://github.com/nebula-plugins/nebula-plugin-plugin/blob/main/build.gradle#L48  and we apply it in https://github.com/nebula-plugins/nebula-plugin-plugin/blob/main/src/main/groovy/nebula/plugin/plugin/NebulaPluginPlugin.groovy#L62C18-L62C28 which I believe is the latest

Wonder if the publish plugin should be addressed first? I'm not familiar with the smoke test but I wonder if it is validating also the plugins that get applied by nebula-plugin-plugin?

**Comment by rpalcolea** [comment]
Hi @ljacomet, thanks for bringing this up!

I'm a little confused here. Looking at the output locally, I see this:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':validatePluginWithId_com_gradle_plugin-publish'.
> Plugin validation failed with 4 problems:
    - Error: Type 'com.gradle.publish.PublishExistingTask' property 'fileRepositoryRoot' is annotated with @InputDirectory but missing a normalization strategy.
      
      Reason: If you don't declare the normalization, outputs can't be re-used between machines or locations on the same machine, therefore caching efficiency drops significantly.
      
      Possible solution: Declare the normalization strategy by annotating the property with either @PathSensitive, @Classpath or @CompileClasspath.
      
      For more information, please refer to https://docs.gradle.org/8.7-20240110080000+0000/userguide/validation_problems.html#missing_normalization_annotation in the Gradle documentation.
    - Warning: Type 'com.gradle.publish.LoginTask' must be annotated either with @CacheableTask or with @DisableCachingByDefault.
      
      Reason: The task author should make clear why a task is not cacheable.
      
      Possible solutions:
        1. Add @DisableCachingByDefault(because = ...).
        2. Add @CacheableTask.
        3. Add @UntrackedTask(because = ...).
      
      For more information, please refer to https://docs.gradle.org/8.7-20240110080000+0000/userguide/validation_problems.html#disable_caching_by_default in the Gradle documentation.
    - Warning: Type 'com.gradle.publish.PublishExistingTask' must be annotated either with @CacheableTask or with @DisableCachingByDefault.
      
      Reason: The task author should make clear why a task is not cacheable.
      
      Possible solutions:
        1. Add @DisableCachingByDefault(because = ...).
        2. Add @CacheableTask.
        3. Add @UntrackedTask(because = ...).
      
      For more information, please refer to https://docs.gradle.org/8.7-20240110080000+0000/userguide/validation_problems.html#disable_caching_by_default in the Gradle documentation.
    - Warning: Type 'com.gradle.publish.PublishTask' must be annotated either with @CacheableTask or with @DisableCachingByDefault.
      
      Reason: The task author should make clear why a task is not cacheable.
      
      Possible solutions:
        1. Add @DisableCachingByDefault(because = ...).
        2. Add @CacheableTask.
        3. Add @UntrackedTask(because = ...).
      
      For more information, please refer to https://docs.gradle.org/8.7-20240110080000+0000/userguide/validation_problems.html#disable_caching_by_default in the Gradle documentation.
  For more on how to annotate task properties, please refer to https://docs.gradle.org/8.7-20240110080000+0000/userguide/incremental_build.html#sec:task_input_output_annotations in the Gradle documentation.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

This suggests that the issue is coming from `com.gradle.publish:plugin-publish-plugin`

We bundle the plugin via https://github.com/nebula-plugins/nebula-plugin-plugin/blob/main/build.gradle#L48  and we apply it in https://github.com/nebula-plugins/nebula-plugin-plugin/blob/main/src/main/groovy/nebula/plugin/plugin/NebulaPluginPlugin.groovy#L62C18-L62C28 which I believe is the latest

Wonder if the publish plugin should be addressed first? I'm not familiar with the smoke test but I wonder if it is validating also the plugins that get applied by nebula-plugin-plugin?

Looking at PublishExistingTask from 1.2.1, is definitely not annotated. So I guess the validation for plugins got stricter since the last release of com.gradle.publish:plugin-publish-plugin ?

**Comment by ljacomet** [comment]
Oh indeed, my bad for not reading the message in detail.

Closing as this needs to be resolved elsewhere. Sorry for the noise.
